[ids]
*

[main]
capslock = overload(nav, esc)    # Esc on tap, nav layer on hold

[nav]
h = left
j = down
k = up
l = right
u = pageup
d = pagedown
0 = home
4 = end
x = delete
w = C-right
b = C-left
n = backspace
